---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-write-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /storage/loki/write
    type: ""
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-loki-write-0
    namespace: observability
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem

