apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: taskmanager
    demo: "true"
  name: taskmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskmanager
  template:
    metadata:
      labels:
        app: taskmanager
      # annotations:
      #   instrumentation.opentelemetry.io/inject-python: "demo"
    spec:
      containers:
      - image: lrbono/taskmanagerflow:latest
        name: taskmanager
        imagePullPolicy: Always
        env:
        - name: "OTEL_PYTHON_LOG_CORRELATION"
          value: "true"
        # - name: "OTEL_PYTHON_LOG_FORMAT"
        #   value: "%(asctime)s %(levelname)s [%(name)s] [%(filename)s:%(lineno)d] [trace_id=%(otelTraceID)s span_id=%(otelSpanID)s resource.service.name=%(otelServiceName)s] - %(message)s"
        #     # value: "%(asctime)s [trace_id=%(otelTraceID)s span_id=%(otelSpanID)s resource.service.name=%(otelServiceName)s] - %(message)s"
        - name: "OTEL_PYTHON_LOG_LEVEL"
          value: "debug"
        ports:
        - containerPort: 80
        # resources: {}
      restartPolicy: Always
