apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: taskmanager
    demo: "true"
  name: taskmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskmanager
  template:
    metadata:
      labels:
        app: taskmanager
      # annotations:
      #   instrumentation.opentelemetry.io/inject-python: "demo"
    spec:
      containers:
      - image: lrbono/taskmanagerflow:latest
        name: taskmanager
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
